# Site settings
title: NetworkCurator.github.io
description: NetworkCurator.github.io 
path: ""
url: "" 

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude:
  - localbuild
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

include:
  - user
  - user/*md
  - developer
  - developer/*md
  - _includes
  - index.md
