# Site settings
title: NetworkCurator
description: NetworkCurator 
path: /
url: "" 

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

include:
  - user
  - user/*md
  - developer
  - developer/*md
  - _includes
  - index.md
